Object.assign(pc, {
    ANIM_INTERRUPTION_NONE: 'NONE',
    ANIM_INTERRUPTION_PREV: 'PREV_STATE',
    ANIM_INTERRUPTION_NEXT: 'NEXT_STATE',
    ANIM_INTERRUPTION_PREV_NEXT: 'PREV_STATE_NEXT_STATE',
    ANIM_INTERRUPTION_NEXT_PREV: 'NEXT_STATE_PREV_STATE',

    ANIM_GREATER_THAN: 'GREATER_THAN',
    ANIM_LESS_THAN: 'LESS_THAN',
    ANIM_GREATER_THAN_EQUAL_TO: 'GREATER_THAN_EQUAL_TO',
    ANIM_LESS_THAN_EQUAL_TO: 'LESS_THAN_EQUAL_TO',
    ANIM_EQUAL_TO: 'EQUAL_TO',
    ANIM_NOT_EQUAL_TO: 'NOT_EQUAL_TO',

    ANIM_PARAMETER_INTEGER: 'INTEGER',
    ANIM_PARAMETER_FLOAT: 'FLOAT',
    ANIM_PARAMETER_BOOLEAN: 'BOOLEAN',
    ANIM_PARAMETER_TRIGGER: 'TRIGGER',

    /**
     * @constant
     * @name pc.ANIM_STATE_START
     * @type {string}
     * @description AnimComponent start state.
     */
    ANIM_STATE_START: 'START',

    /**
     * @constant
     * @name pc.ANIM_STATE_START
     * @type {string}
     * @description AnimComponent end state.
     */
    ANIM_STATE_END: 'END'
});
