export var ANIM_INTERRUPTION_NONE = 'NONE';
export var ANIM_INTERRUPTION_PREV = 'PREV_STATE';
export var ANIM_INTERRUPTION_NEXT = 'NEXT_STATE';
export var ANIM_INTERRUPTION_PREV_NEXT = 'PREV_STATE_NEXT_STATE';
export var ANIM_INTERRUPTION_NEXT_PREV = 'NEXT_STATE_PREV_STATE';

export var ANIM_GREATER_THAN = 'GREATER_THAN';
export var ANIM_LESS_THAN = 'LESS_THAN';
export var ANIM_GREATER_THAN_EQUAL_TO = 'GREATER_THAN_EQUAL_TO';
export var ANIM_LESS_THAN_EQUAL_TO = 'LESS_THAN_EQUAL_TO';
export var ANIM_EQUAL_TO = 'EQUAL_TO';
export var ANIM_NOT_EQUAL_TO = 'NOT_EQUAL_TO';

export var ANIM_PARAMETER_INTEGER = 'INTEGER';
export var ANIM_PARAMETER_FLOAT = 'FLOAT';
export var ANIM_PARAMETER_BOOLEAN = 'BOOLEAN';
export var ANIM_PARAMETER_TRIGGER = 'TRIGGER';

export var ANIM_STATE_START = 'START';
export var ANIM_STATE_END = 'END';
