// Fragment shader template for GSplatProcessor - processes splat data from src to dst streams
export default /* glsl */`

// Texture size uniforms
uniform uint splatTextureSize;
uniform uint dstTextureSize;

// Shared splat identification (index, uv) and setSplat() helper
#include "gsplatSplatVS"

// Input stream declarations (generated by GSplatFormat.getInputDeclarations)
#include "gsplatProcessInputVS"

// Output write functions (generated by GSplatFormat.getOutputDeclarations)
#include "gsplatProcessOutputVS"

// Format-specific read code (included when "default" stream is used)
#include "gsplatProcessReadVS"

// User's process code - defines process() function and any declarations
#include "gsplatProcessChunk"

void main(void) {
    // Fragment coordinates give us the destination splat index
    ivec2 fragCoords = ivec2(gl_FragCoord.xy);
    
    // Linear index of the destination splat
    int splatIndex = fragCoords.y * int(dstTextureSize) + fragCoords.x;
    
    // Initialize global splat for sampling
    // Note: splat.uv assumes 1:1 mapping using splatTextureSize. When sizes differ,
    // call setSplat() with a different index in user code.
    setSplat(uint(splatIndex));
    
    // Call user's process function
    process();
}
`;
