// Fragment shader template for GSplatProcessor - processes splat data from src to dst streams
export default /* glsl */`

// SplatSource struct for reading splat data
struct SplatSource {
    uint id;            // splat id
    ivec2 uv;           // splat uv for texture sampling
};

// splatUV is set by getCenter and used by load functions
ivec2 splatUV;

// Texture size uniform
uniform uint splatTextureSize;

// User uniform declarations
#include "gsplatProcessDeclarationsVS"

// Input stream declarations (generated by GSplatFormat.getInputDeclarations)
#include "gsplatProcessInputVS"

// Output write functions (generated by GSplatFormat.getOutputDeclarations)
#include "gsplatProcessOutputVS"

// Format-specific read code (included when "default" stream is used)
#include "gsplatProcessReadVS"

void main(void) {
    // Fragment coordinates give us the splat index
    ivec2 fragCoords = ivec2(gl_FragCoord.xy);
    
    // Linear index of the splat
    int splatIndex = fragCoords.y * int(splatTextureSize) + fragCoords.x;
    
    // Create SplatSource for sampling (uv matches fragCoords since textures use same size)
    SplatSource source;
    source.id = uint(splatIndex);
    source.uv = fragCoords;
    
    // Set splatUV for load functions
    splatUV = source.uv;
    
    // User's processing code
    #include "gsplatProcessChunk"
}
`;
