import * as observer from '@playcanvas/observer';
import * as pcuiReal from '@playcanvas/pcui';
import * as pcui from '@playcanvas/pcui/react';
import React from 'react';
//import 'pc-alias';
import * as pcx from 'playcanvas-extras';
window.pcuiReal = pcuiReal;
window.observer = observer;
window.pcui = window.top.pcui || pcui;
window.React = window.top.React || React;
window.pcx = pcx;
