pc.extend(pc, function () {
    /**
     * @component
     * @name pc.LightComponent
     * @class The Light Component enables the Entity to light the scene. The light can be one of the
     * following types:
     * <ul>
     * <li><strong>directional</strong>: A directional light. The position of the attached entity has no effect. </li>
     * <li><strong>point</strong>: A point light.</li>
     * <li><strong>spot</strong>: A spot light.</li>
     * </ul>
     * @constructor Creates a new LightComponent. The constructor is for internal use only. To create a new Component use {@link pc.LightComponentSystem#addComponent}.
     * @param {pc.LightComponentSystem} system The ComponentSystem that created this Component
     * @param {pc.Entity} entity The Entity that this Component is attached to.
     * @property {String} type The type of light.
     * <ul>
     * <li><strong>directional</strong>: A light that is infinitely far away and lights the entire scene from one direction.</li>
     * <li><strong>point</strong>: A light that illuminates in all directions from a point.</li>
     * <li><strong>spot</strong>: A light that illuminates a cone.</li>
     * </ul>
     * @property {pc.Color} color The Color of the light
     * @property {Boolean} enabled Enable or disable the light
     * @property {Number} intensity The brightness of the light.
     * @property {Boolean} castShadows If enabled the light will cast shadows.
     * @property {Number} shadowDistance The distance from the viewpoint beyond which shadows are no longer rendered. (Directional lights only)
     * @property {Number} shadowResolution The size of the texture used for the shadow map. Avaialable sizes are 64, 128, 256, 512, 1024, 2048.
     * @property {Number} shadowBias The depth bias for tuning the appearance of the shadow mapping generated by this light.
     * @property {Number} normalOffsetBias Normal offset depth bias.
     * @property {Number} range The range of the light. (Point and spot lights only)
     * @property {Number} innerConeAngle The angle at which the spotlight cone starts to fade off. (Spot lights only)
     * @property {Number} outerConeAngle The angle at which the spotlight cone has faded to nothing. (Spot lights only)
     * @property {Number} falloffMode Controls the rate at which a light attentuates from its position. (Point and spot lights only)
     * <ul>
     * <li><strong>{@link pc.LIGHTFALLOFF_LINEAR}</strong>: Linear.</li>
     * <li><strong>{@link pc.LIGHTFALLOFF_INVERSESQUARED}</strong>: Inverse squared.</li>
     * </ul>
     * @extends pc.Component
     */
    var LightComponent = function LightComponent(system, entity) {
        this.on("set_type", this.onSetType, this);
        this.on("set_color", this.onSetColor, this);
        this.on("set_intensity", this.onSetIntensity, this);
        this.on("set_castShadows", this.onSetCastShadows, this);
        this.on("set_shadowDistance", this.onSetShadowDistance, this);
        this.on("set_shadowResolution", this.onSetShadowResolution, this);
        this.on("set_shadowBias", this.onSetShadowBias, this);
        this.on("set_normalOffsetBias", this.onSetNormalOffsetBias, this);
        this.on("set_range", this.onSetRange, this);
        this.on("set_innerConeAngle", this.onSetInnerConeAngle, this);
        this.on("set_outerConeAngle", this.onSetOuterConeAngle, this);
        this.on("set_falloffMode", this.onSetFalloffMode, this);
        this.on("set_shadowType", this.onSetShadowType, this);
        this.on("set_shadowUpdateMode", this.onSetShadowUpdateMode, this);
        this.on("set_mask", this.onSetMask, this);
    };

    LightComponent = pc.inherits(LightComponent, pc.Component);

    Object.defineProperty(LightComponent.prototype, "enable", {
        get: function() {
            console.warn("WARNING: enable: Property is deprecated. Query enabled property instead.");
            return this.enabled;
        },
        set: function(value) {
            console.warn("WARNING: enable: Property is deprecated. Set enabled property instead.");
            this.enabled = value;
        },
    });

    pc.extend(LightComponent.prototype, {
        onSetType: function (name, oldValue, newValue) {
            if (oldValue === newValue)
                return;

            this.system.changeType(this, oldValue, newValue);

            // refresh light properties because changing the type does not reset the
            // light properties
            this.refreshProperties();
        },

        refreshProperties: function() {
            this.onSetCastShadows("castShadows", this.castShadows, this.castShadows);
            this.onSetColor("color", this.color, this.color);
            this.onSetIntensity("intensity", this.intensity, this.intensity);
            this.onSetShadowDistance("shadowDistance", this.shadowDistance, this.shadowDistance);
            this.onSetShadowResolution("shadowResolution", this.shadowResolution, this.shadowResolution);
            this.onSetShadowBias("shadowBias", this.shadowBias, this.shadowBias);
            this.onSetNormalOffsetBias("normalOffsetBias", this.normalOffsetBias, this.normalOffsetBias);
            this.onSetRange("range", this.range, this.range);
            this.onSetInnerConeAngle("innerConeAngle", this.innerConeAngle, this.innerConeAngle);
            this.onSetOuterConeAngle("outerConeAngle", this.outerConeAngle, this.outerConeAngle);
            this.onSetFalloffMode("falloffMode", this.falloffMode, this.falloffMode);
            this.onSetShadowType("shadowType", this.shadowType, this.shadowType);
            this.onSetShadowUpdateMode("shadowUpdateMode", this.shadowUpdateMode, this.shadowUpdateMode);
            this.onSetMask("mask", this.mask, this.mask);

            if (this.enabled && this.entity.enabled)
                this.onEnable();
        },

        updateShadow: function() {
            this.light.updateShadow();
        },

        onSetCastShadows: function (name, oldValue, newValue) {
            this.light.setCastShadows(newValue);
        },

        onSetColor: function (name, oldValue, newValue) {
            this.light.setColor(newValue);
        },

        onSetIntensity: function (name, oldValue, newValue) {
            this.light.setIntensity(newValue);
        },

        onSetShadowDistance: function (name, oldValue, newValue) {
            if (this.data.type !== 'directional')
                return;

            this.light.setShadowDistance(newValue);
        },

        onSetShadowResolution: function (name, oldValue, newValue) {
            this.light.setShadowResolution(newValue);
        },

        onSetShadowBias: function (name, oldValue, newValue) {
            // remap the value to the range needed by the shaders
            this.light.setShadowBias(-0.01 * newValue);
        },

        onSetNormalOffsetBias: function (name, oldValue, newValue) {
            this.light.setNormalOffsetBias(newValue);
        },

        onSetRange: function (name, oldValue, newValue) {
            if (this.data.type !== 'point' && this.data.type !== 'spot')
                return;

            this.light.setAttenuationEnd(newValue);
        },

        onSetInnerConeAngle: function (name, oldValue, newValue) {
            if (this.data.type !== 'spot')
                return;

            this.light.setInnerConeAngle(newValue);
        },

        onSetOuterConeAngle: function (name, oldValue, newValue) {
            if (this.data.type !== 'spot')
                return;

            this.light.setOuterConeAngle(newValue);
        },

        onSetFalloffMode: function (name, oldValue, newValue) {
            if (this.data.type !== 'point' && this.data.type !== 'spot')
                return;

            this.light.setFalloffMode(newValue);
        },

        onSetShadowType: function (name, oldValue, newValue) {
            this.light.setShadowType(newValue);
        },

        onSetShadowUpdateMode: function (name, oldValue, newValue) {
            this.light.shadowUpdateMode = newValue;
        },

        onSetMask: function (name, oldValue, newValue) {
            this.light.mask = newValue;
        },

        onEnable: function () {
            LightComponent._super.onEnable.call(this);

            this.light.setEnabled(true);

            var model = this.data.model;
            if (! model)
                return;

            var scene = this.system.app.scene;
            if (scene.containsModel(model))
                return;

            scene.addModel(model);
        },

        onDisable: function () {
            LightComponent._super.onDisable.call(this);

            this.light.setEnabled(false);

            var model = this.data.model;
            if (! model)
                return;

            this.system.app.scene.removeModel(model);
        }
    });

    return {
        LightComponent: LightComponent
    };
}());
