export const ANIM_INTERRUPTION_NONE = 'NONE';
export const ANIM_INTERRUPTION_PREV = 'PREV_STATE';
export const ANIM_INTERRUPTION_NEXT = 'NEXT_STATE';
export const ANIM_INTERRUPTION_PREV_NEXT = 'PREV_STATE_NEXT_STATE';
export const ANIM_INTERRUPTION_NEXT_PREV = 'NEXT_STATE_PREV_STATE';

export const ANIM_GREATER_THAN = 'GREATER_THAN';
export const ANIM_LESS_THAN = 'LESS_THAN';
export const ANIM_GREATER_THAN_EQUAL_TO = 'GREATER_THAN_EQUAL_TO';
export const ANIM_LESS_THAN_EQUAL_TO = 'LESS_THAN_EQUAL_TO';
export const ANIM_EQUAL_TO = 'EQUAL_TO';
export const ANIM_NOT_EQUAL_TO = 'NOT_EQUAL_TO';

export const ANIM_PARAMETER_INTEGER = 'INTEGER';
export const ANIM_PARAMETER_FLOAT = 'FLOAT';
export const ANIM_PARAMETER_BOOLEAN = 'BOOLEAN';
export const ANIM_PARAMETER_TRIGGER = 'TRIGGER';

export const ANIM_BLEND_1D = '1D';
export const ANIM_BLEND_2D_DIRECTIONAL = '2D_DIRECTIONAL';
export const ANIM_BLEND_2D_CARTESIAN = '2D_CARTESIAN';
export const ANIM_BLEND_DIRECT = 'DIRECT';

export const ANIM_STATE_START = 'START';
export const ANIM_STATE_END = 'END';
export const ANIM_STATE_ANY = 'ANY';
