import glslComposeDofPS from '../../../scene/shader-lib/glsl/chunks/render-pass/frag/compose/compose-dof.js';
import wgslComposeDofPS from '../../../scene/shader-lib/wgsl/chunks/render-pass/frag/compose/compose-dof.js';
import { CameraFrameEffect } from '../camera-frame-effect.js';
import { COMPOSESLOT_HDR, FRAMERESOURCE_DEPTH, FRAMERESOURCE_SCENECOLORHALF } from '../constants.js';
import { FramePassDof } from '../frame-pass-dof.js';

/**
 * @import { CameraFrameEffectContext, CameraFrameEffectPasses, CameraFrameEffectResources } from '../camera-frame-effect.js'
 * @import { GraphicsDevice } from '../../../platform/graphics/graphics-device.js'
 */

/**
 * The Depth of Field (DOF) effect, a technique used to simulate the optical effect where objects
 * at certain distances appear sharp while others are blurred, enhancing the perception of focus
 * and depth in the rendered scene.
 *
 * The blur is generated by passes the effect owns, from the scene depth and the scene color, and
 * mixed into the scene in linear HDR space, before tone mapping.
 *
 * Every {@link CameraFrame} constructs and registers one, available as {@link CameraFrame#dof}.
 *
 * @category Graphics
 */
class DofEffect extends CameraFrameEffect {
    /**
     * Whether DoF is enabled. Defaults to false.
     *
     * @type {boolean}
     */
    enabled = false;

    /**
     * Whether the near blur is enabled. Defaults to false.
     *
     * @type {boolean}
     */
    nearBlur = false;

    /**
     * The distance at which the focus is set. Defaults to 100.
     *
     * @type {number}
     */
    focusDistance = 100;

    /**
     * The range around the focus distance where the focus is sharp. Defaults to 10.
     *
     * @type {number}
     */
    focusRange = 10;

    /**
     * The radius of the blur effect, typically 2-10 range. Defaults to 3.
     *
     * @type {number}
     */
    blurRadius = 3;

    /**
     * The number of rings in the blur effect, typically 3-8 range. Defaults to 4.
     *
     * @type {number}
     */
    blurRings = 4;

    /**
     * The number of points in each ring of the blur effect, typically 3-8 range. Defaults to 5.
     *
     * @type {number}
     */
    blurRingPoints = 5;

    /**
     * Whether the high quality implementation is used, which blurs the full resolution scene
     * instead of a half resolution copy of it. This will have a higher performance cost, but will
     * produce better quality results. Defaults to true.
     *
     * @type {boolean}
     */
    highQuality = true;

    /**
     * The passes generating the blur, while the effect's passes exist.
     *
     * @type {FramePassDof|null}
     * @private
     */
    _pass = null;

    /**
     * Whether the existing passes blur the full resolution scene.
     *
     * @type {boolean}
     * @private
     */
    _highQuality = false;

    /**
     * @param {GraphicsDevice} device - The graphics device.
     */
    constructor(device) {
        super(device, 'dof', {
            slot: COMPOSESLOT_HDR,
            glsl: glslComposeDofPS,
            wgsl: wgslComposeDofPS,
            debugViews: ['dofcoc', 'dofblur'],
            requires: [FRAMERESOURCE_DEPTH, FRAMERESOURCE_SCENECOLORHALF]
        });
    }

    /**
     * @returns {string} The key.
     * @ignore
     */
    buildKey() {
        // the near blur and the quality change the passes and their render targets
        return `${this.nearBlur}-${this.highQuality}`;
    }

    /**
     * @param {CameraFrameEffectResources} resources - The frame resources the effect requires.
     * @param {CameraFrameEffectPasses} passes - The arrays to add the passes to, per stage.
     * @ignore
     */
    createPasses(resources, passes) {

        // the circle of confusion is rendered at the size of the scene, which the depth has
        this._highQuality = this.highQuality;
        this._pass = new FramePassDof(this.device, this.cameraFrame.cameraComponent, resources.depth.texture,
            resources.sceneColorHalf, this.highQuality, this.nearBlur);
        passes.postTemporal.push(this._pass);
    }

    /**
     * @ignore
     */
    destroyPasses() {
        this._pass?.destroy();
        this._pass = null;
        this._highQuality = false;
    }

    update() {
        const pass = this._pass;
        pass.focusDistance = this.focusDistance;
        pass.focusRange = this.focusRange;
        pass.blurRadius = this.blurRadius;
        pass.blurRings = this.blurRings;
        pass.blurRingPoints = this.blurRingPoints;

        // the low quality blur is a quarter resolution texture, which the composition upscales
        this.setUniform('cocTexture', pass.cocTexture);
        this.setUniform('blurTexture', pass.blurTexture);
        this.setDefine('DOF_UPSCALE', !this._highQuality);
    }

    /**
     * @param {CameraFrameEffectContext} frame - The values of this frame.
     */
    frameUpdate(frame) {
        // the high quality blur reads the full resolution scene, which alternates between two
        // textures with temporal anti-aliasing
        if (this._highQuality) {
            this._pass.setSceneTexture(frame.sceneTexture);
        }
    }
}

export { DofEffect };
