import { readFileSync } from 'fs';
import { resolve } from 'path';

/* eslint-disable-next-line import/no-unresolved */
import { ArrayType, Converter, DeclarationReflection, IntrinsicType, ReflectionFlag, ReflectionKind, ReferenceType, TypeScript as ts, UnionType } from 'typedoc';

/**
 * Determines whether a TypeScript declaration is annotated with an `@ignore` (or `@hidden`) JSDoc
 * modifier tag, meaning it should be excluded from the generated documentation.
 *
 * @param {import('typedoc').TypeScript.Declaration} declaration - The TypeScript declaration node.
 * @returns {boolean} True if the declaration is tagged `@ignore` or `@hidden`.
 */
function hasIgnoreTag(declaration) {
    // Tags attached directly to the declaration (covers regular symbols such as classes, functions
    // and properties).
    const tags = [...(ts.getJSDocTags(declaration) ?? [])];

    // For `@typedef` (and `@callback`) the symbol's declaration is the tag node itself, so sibling
    // modifier tags such as `@ignore` live on the hosting JSDoc comment block rather than on the
    // tag. Pull those in as well.
    if (declaration.parent && ts.isJSDoc(declaration.parent)) {
        tags.push(...(declaration.parent.tags ?? []));
    }

    return tags.some((tag) => {
        const name = tag.tagName?.escapedText;
        return name === 'ignore' || name === 'hidden';
    });
}

/**
 * Extract property types from JSDoc in a .js file.
 *
 * @param {string} filePath - The path to the .js file.
 * @returns {Map<string, string>} A map of property names to types.
 */
function getProperties(filePath) {
    const data = readFileSync(resolve(process.cwd(), filePath), 'utf-8');
    // eslint-disable-next-line regexp/no-dupe-disjunctions
    const docBlocks = data.match(/\/\*\*([^*]|[\r\n]|(\*+([^*/]|[\r\n])))*\*+\//g);
    const properties = new Map();

    if (docBlocks) {
        docBlocks.forEach((block) => {
            const propertyLines = block.match(/@property\s*\{[^}]+\}[^*]*/g);

            if (propertyLines) {
                propertyLines.forEach((line) => {
                    const match = line.match(/@property\s*\{([^}]+)\}\s*(\w+)/);

                    if (match) {
                        let type = match[1].trim();
                        const name = match[2].trim();

                        // Simplify complex import types.
                        type = type.replace(/import\(['"]([^'"]+)['"]\)\.(\w+)/g, (_, p1, p2) => p2);

                        properties.set(name, type);
                    }
                });
            }
        });
    }

    return properties;
}

/**
 * This Typedoc plugin adds missing PlayCanvas API symbols to the Typedoc reflection graph. The
 * symbols are missing because they are generated by `Object.defineProperty` in the PlayCanvas
 * sourcebase. The TypeScript compiler is unable to detect them, either in the code or in the
 * JSDoc comments (specified via \@property tags).
 *
 * @param {import('typedoc').Application} app - The Typedoc application.
 */
function load(app) {
    const classes = new Map([
        ['ButtonComponent', './src/framework/components/button/component.js'],
        ['CollisionComponent', './src/framework/components/collision/component.js'],
        ['ElementComponent', './src/framework/components/element/component.js'],
        ['LightComponent', './src/framework/components/light/component.js'],
        ['ParticleSystemComponent', './src/framework/components/particle-system/component.js'],
        ['ScrollbarComponent', './src/framework/components/scrollbar/component.js'],
        ['ScrollViewComponent', './src/framework/components/scroll-view/component.js'],
        ['StandardMaterial', './src/scene/materials/standard-material.js']
    ]);

    // Collect reflections that `typedoc-plugin-missing-exports` re-introduces even though their
    // source declaration is tagged `@ignore`. That plugin records referenced-but-unexported
    // symbols during conversion and re-converts them at resolve time, after TypeDoc's own
    // `@ignore` removal pass has already run - so the resulting reflection has lost its `@ignore`
    // tag and leaks into the public docs (e.g. the internal `ShaderVariantParams` typedef, which
    // is only referenced by `@ignore` methods). We can't detect this from the reflection's stripped
    // comment, so inspect the original TypeScript declaration here, while the symbol is still
    // available, and remember which reflections to drop.
    const ignoredReflections = new Set();
    app.converter.on(Converter.EVENT_CREATE_DECLARATION, (/** @type {import('typedoc').Context} */ context, reflection) => {
        const declarations = context.getSymbolFromReflection(reflection)?.declarations;

        // Require *every* declaration to be tagged, not just one: a get/set accessor is backed by
        // two declarations and tagging only the setter `@ignore` (as `Entity#guid` and
        // `Texture#srgb` do) is meant to hide the setter while keeping the public getter, so the
        // reflection as a whole must stay.
        if (declarations?.length && declarations.every(hasIgnoreTag)) {
            ignoredReflections.add(reflection);
        }
    });

    app.converter.on(Converter.EVENT_RESOLVE_END, (/** @type {import('typedoc').Context} */ context) => {
        // Sweep away any top-level Accessor reflections that `typedoc-plugin-missing-exports` has
        // incorrectly hoisted out of their owning class into the project root. These show up as
        // orphan entries under the "Other" category on the generated index page, with broken
        // self-links to anchors that don't exist. The canonical documentation for each accessor
        // lives on its owning class's page; removing the project-root duplicates does not affect
        // those class-member reflections.
        const orphans = context.project.children?.filter(child => child.kind === ReflectionKind.Accessor) ?? [];
        for (const orphan of orphans) {
            context.project.removeReflection(orphan);
        }

        // Drop the `@ignore`-tagged reflections gathered above. Guard against reflections that
        // TypeDoc already removed (the original, pre-leak conversion), removing only those still
        // present in the project.
        for (const reflection of ignoredReflections) {
            if (context.project.getReflectionById(reflection.id) === reflection) {
                context.project.removeReflection(reflection);
            }
        }
        ignoredReflections.clear();
    });

    app.converter.on(Converter.EVENT_RESOLVE_BEGIN, (/** @type {import('typedoc').Context} */ context) => {
        const getReference = (type) => {
            const reflection = context.project.children.find(child => child.name === type && child.kind === ReflectionKind.Class);
            if (!reflection) {
                console.error(`Unable to find class ${type}`);
            }
            return reflection;
        };

        classes.forEach((filePath, className) => {
            const reflection = getReference(className);

            /**
             * Returns the reference type matching the specified class name.
             *
             * @param {string} type - The class name.
             * @returns {ReferenceType} The reference type.
             */
            const getReferenceType = (type) => {
                const reference = getReference(type);
                return reference ? new ReferenceType(type, reference, context.project) : undefined;
            };

            /**
             * Returns the Typedoc type matching the specified JSDoc type. This can include a union type (|).
             *
             * @param {string} type - The JSDoc type string.
             * @returns {import('typedoc').Type} The Typedoc type.
             */
            const getType = (type) => {
                if (type.includes('|')) {
                    const types = type.split('|');
                    return new UnionType(types.map(type => getType(type)));
                }

                switch (type) {
                    case 'null':
                        return new IntrinsicType('null');
                    case 'boolean':
                        return new IntrinsicType('boolean');
                    case 'number':
                        return new IntrinsicType('number');
                    case 'number[]':
                        return new ArrayType(new IntrinsicType('number'));
                    case 'string':
                        return new IntrinsicType('string');
                    default:
                        return getReferenceType(type);
                }
            };

            const properties = getProperties(filePath);

            // Get just the @property definitions from the class' JSDoc block
            const blockTags = reflection.comment.blockTags.filter(blockTag => blockTag.tag === '@property');

            // Convert all @property tags on StandardMaterial to actual child properties of StandardMaterial
            for (const blockTag of blockTags) {
                const newProperty = new DeclarationReflection(blockTag.name, ReflectionKind.Property, reflection);

                const type = properties.get(blockTag.name);

                newProperty.type = getType(type);

                // Mark the new property as public
                newProperty.setFlag(ReflectionFlag.Public, true);

                // Add the new property to the class
                if (!reflection.children) {
                    reflection.children = [];
                }
                reflection.addChild(newProperty);
            }
        });
    });
}

export { load };
